version: "3.8"
services:
  cruise-control:
    image: cruise-control:latest
    network_mode: host
    ports:
      - 5010:5010
      - 5011:5011
    volumes:
      - ./pwd:/pwd
      - ./src:/src
    entrypoint: tail -F /dev/null
